#!/bin/bash
#install root bash-- run as sudo
if [ "$EUID" -ne 0 ]
        then echo "Please run as superuser"
        exit
fi
#required apps
apt install figlet fortune
#replace root bash
sudo mv /root/.bashrc /root/.bashrc-old
sudo curl https://raw.githubusercontent.com/Kristopherr/Best-Bash/master/.bashrc > /root/.bashrc
#replace user bash
mv /home/$SUDO_USER/.bashrc /home/$SUDO_USER/.bashrc-old
curl https://raw.githubusercontent.com/Kristopherr/Best-Bash/master/.bashrc > /home/$SUDO_USER/.bashrc
