#!/bin/bash
#install root bash-- run as sudo
if [ "$EUID" -ne 0 ]; then echo "This will only change user bash. To change root run as superuser."; fi
echo
echo "1) Revert to Original Bash"
echo "2) Replace/Update Better Bash"
echo "3) Install required packages: figlet and dnsutils"
echo
read choice
if [ "$choice" == 1 ] && [ "$EUID" -ne 0 ]; then 
    cp /etc/skel/.bashrc /home/$USER/.bashrc && echo "Replaced --> /home/$USER/.bashrc"
    cp /etc/skel/.profile /home/$USER/.profile && echo "Replaced --> /home/$USER/.profile"
    cp /etc/skel/.bash_logout /home/$USER/.bash_logout && echo "Replaced --> /home/$USER/.bash_logout" && echo "Success"
elif [ "$choice" == 1 ] && [ "$EUID" -eq 0 ]; then
    cp /etc/skel/.bashrc /root/.bashrc && echo "Reverted --> /root/.bashrc"
    cp /etc/skel/.profile /root/.profile && echo "Reverted --> /root/.profile"
    cp /etc/skel/.bash_logout /root/.bash_logout && echo "Reverted --> /root/.bash_logout" && echo "Success"
elif [ "$choice" == 2 ] && [ "$EUID" -eq 0 ]; then
    curl https://raw.githubusercontent.com/Kristopherr/Best-Bash/master/.bashrc > /root/.bashrc
elif [ "$choice" == 2 ] && [ "$EUID" -ne 0 ]; then   
    curl https://raw.githubusercontent.com/Kristopherr/Best-Bash/master/.bashrc > /home/$USER/.bashrc
elif [ "$choice" == 3 ]; then sudo apt install figlet dnsutils; fi
